#!/bin/bash

run_file() {
  if [ -f Bakefile ]; then
    bake_file=Bakefile
    bake_script=`mktemp -t bake_tmp.XXX`
    while read -r line; do
      echo "$line" >> $bake_script
    done <<< "`cat $bake_file`"
    cat $bake_script | bash --verbose
  else
    echo "bake: Aborted. No Bakefile found."
  fi
}

run_file
